spring:
  datasource:
    url: jdbc:postgresql://database-springboot-abds-alunos.cjveivbxssua.us-east-1.rds.amazonaws.com:5432/database-springboot-abds-alunos
    username: postgres
    password: ${{ secrets.PROD_DB_PASSWORD }}
    name: tb_alunos
